# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A star algorithm to calculate the shortest path on a graph object
NULL

#' A star algorithm that takes a heuristinc funciton as argument (it is slower)
NULL

Astar <- function(graph, source, goal, hFnc = "euclidean", hCoef = 1) {
    .Call(`_pathFindeR_Astar`, graph, source, goal, hFnc, hCoef)
}

Astarhfnc <- function(graph, source, goal, hFnc, hCoef = 1) {
    .Call(`_pathFindeR_Astarhfnc`, graph, source, goal, hFnc, hCoef)
}

DFS <- function(graph, v) {
    .Call(`_pathFindeR_DFS`, graph, v)
}

#' Erdős–Rényi model for random graph creation
NULL

ErdosRenyiPmodel <- function(n, p) {
    .Call(`_pathFindeR_ErdosRenyiPmodel`, n, p)
}

haversine <- function(lon1, lat1, lon2, lat2) {
    .Call(`_pathFindeR_haversine`, lon1, lat1, lon2, lat2)
}

euclidean <- function(lon1, lat1, lon2, lat2) {
    .Call(`_pathFindeR_euclidean`, lon1, lat1, lon2, lat2)
}

manhattan <- function(lon1, lat1, lon2, lat2) {
    .Call(`_pathFindeR_manhattan`, lon1, lat1, lon2, lat2)
}

canberra <- function(lon1, lat1, lon2, lat2) {
    .Call(`_pathFindeR_canberra`, lon1, lat1, lon2, lat2)
}

